#!/bin/bash

# This script is a "wrapper" shell script to facilitate running the est_comms_link.py
# Python script from the RPG scripts directory.
#

if grep -q "7.9" /etc/redhat-release ; then
        echo 'RHEL7'
        /usr/bin/python /home/pmccrone/python/src/ecl/est_comms_link_pm_v2.py $*
else
        echo 'RHEL8 or higher'
        /usr/bin/python2 /home/pmccrone/python/src/ecl/est_comms_link_pm_v2.py $*
fi


